name: sfacts
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.5
  - pytorch=1.10.0
  - torchvision=0.11.1
  - torchaudio=0.10.0
  - ipython=7.30.0
  - jupyterlab=3.2.4
  - xarray=0.20.1
  - netCDF4=1.5.8
  - matplotlib=3.5.0
  - pyro-ppl=1.7.0
  - torch-optimizer=0.3.0
  - pandas=1.3.4
  - seaborn=0.11.2
  - tqdm=4.62.3
  - scipy=1.7.3
  - numpy=1.21.4
  - scikit-learn=0.5.6
  - scikit-bio=1.0.1
  - line_profiler=3.3.1
  - memory_profiler=0.58.0
  - pip:
    - -e https://github.com/bsmith89/StrainFacts@egg=sfacts
