name: StrainFacts

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    env:
      DATADIR: data
    strategy:
      matrix:
        python-version: [3.9]
        build_type: [Release]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        mamba-version: "*"
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        environment-file: conda_env.yaml
        activate-environment: strainfacts
    - name: pip install
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/StrainFacts/
      run: |
        pip install -r requirements.pip
        pip install -e .
    - name: run tests
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/StrainFacts/
      run: |
        make clean
        make test